### ISSUE TITLE
Regarding other project

### ISSUE THREAD

**Issue by danielywang** [sha186/xv6104#1]
Deleted after acknowledgement

**Comment by sha186** [comment]
I have notified her and she will take down it soon. We loved your project
idea and we did not intend to copy your code but wanted to have a look at
it. We are really sorry for that. But for sure we would love to work on the
project again in the future with all due credits to your team. Thanks for
an amazing contribution to the society and we are sorry for the
inconvenience caused.

**Comment by danielywang** [comment]
Thank you. I am glad it was a misunderstanding rather than a malicious attempt. My email is y444444y@hotmail.com. I look forward to discussing this further.

**Comment by sha186** [comment]
Thank you for your understanding.
